<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
    کوویدکاوی
</font>
</h1>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در این تمرین می‌خواهیم داده‌های مربوط به وضعیت کووید-۱۹ در کشورهای مختلف جهان در یک روز از سال ۲۰۲۰ را کمی تحلیل کنیم و با پاسخ دادن به پرسش‌هایی از آن با کتابخانه‌ی <code>pandas</code> بیشتر کار کنیم.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه‌داده‌
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
ابتدا داده‌ها را از فایل <code>covid19-11-10-2020.csv</code> بخوانید و در متغیر <code>covid_data</code> ذخیره کنید.
</font>
</p>

In [3]:
import pandas as pd

In [4]:
covid_data = pd.read_csv('covid19-11-10-2020.csv')
covid_data.head()

,Unnamed: 0,FIPS,Admin2,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,Combined_Key,Incident_Rate,Case_Fatality_Ratio
0,0,NaN,NaN,NaN,Afghanistan,2020-11-11 05:25:30,33.93911,67.709953,42297,1574,34954.0,5769.0,Afghanistan,108.653487,3.721304
1,1,NaN,NaN,NaN,Albania,2020-11-11 05:25:30,41.15330,20.168300,25294,579,12353.0,12362.0,Albania,878.935298,2.289080
2,2,NaN,NaN,NaN,Algeria,2020-11-11 05:25:30,28.03390,1.659600,63446,2077,42626.0,18743.0,Algeria,144.685270,3.273650
3,3,NaN,NaN,NaN,Andorra,2020-11-11 05:25:30,42.50630,1.521800,5477,75,4405.0,997.0,Andorra,7088.591212,1.369363
4,4,NaN,NaN,NaN,Angola,2020-11-11 05:25:30,-11.20270,17.873900,12816,308,6036.0,6472.0,Angola,38.994388,2.403246

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
    <font face="vazir" size=3>
        همان‌طور که احتمالاً دیده‌اید، این مجموعه‌داده دارای ۱۴ ویژگی/ستون است که به معرفی برخی از آن‌ها که مهم‌ترند می‌پردازیم. البته که شما باید تشخیص بدهید که در هر سوال کدام موارد به کار می‌آیند.
        <br>
       - ستون  <code>Country_Region</code>: مشخص است که نام کشور یا منطقه را مشخص می‌کند. دقت کنید که شاید لازم باشد بررسی کنید که آیا تعداد سطرها با تعداد کشورها برابر است و به بیان دیگر به ازای هر منطقه یا کشور فقط یک سطر دیتا وجود دارد یا خیر.
        <br>
        - ستون‌های <code>Long</code> و <code>Lat</code>: طول و عرض جفرافیایی کشور/منطقه را بیان می‌کند.
        <br>
        - ستون <code>Confirmed</code>: تعداد موارد تاییدشده‌ی ابتلا به ویروس
        <br>
        - ستون <code>Deaths</code>: تعداد موارد فوت‌شده
        <br>
        - ستون <code>Recovered</code>: تعداد موارد بهبودیافته
        <br>
        - ستون <code>Active</code>: تعداد موارد فعال (که از تفاضل مجموع فوتی‌ها و بهبودیافتگان از موارد تایید شده نیز به‌دست می‌آید.)
        <br>
        - ستون <code>Incident_Rate</code>: بیانگر تعداد موارد در هر ۱۰۰۰۰۰ نفر است.
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:red">نکته‌:</b>
در هر سوال که از شما خواسته‌شده پاسخ را در قالب فایلی با فرمت <code>csv</code> ذخیره کنید، لازم نیست نام ستون‌ها را ذخیره کنید (به بیان دیگر لازم نیست  <code>header</code> داشته باشند).
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت اول‌
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
     در ابتدا می‌خواهیم ببینیم ۱۰ کشور با بیشترین تعداد موارد  کدام‌اند. برای این کار می‌توانیم از
ستون  <code>Incident_Rate</code> استفاده کنیم. البته برای این‌که به‌نوعی مجموع تقریبی موارد را از این ستون محاسبه کنیم می‌توانیم از متد <code>apply</code>  استفاده کنیم و ستونی جدید به نام <code>Total_Cases</code> اضافه کنیم که از حاصل ضرب ۱۰۰۰۰۰ در مقادیر ستون <code>Incident_Rate</code> توسط تابع <code>apply</code> به‌دست می‌آیند.
<br>
پاسخ شما باید دارای ۱۰ ردیف و ۲ ستون باشد که نام کشور/منطقه و <code>Total_Cases</code> را شامل می‌شود و آن را در فایلی به نام <code>top10cases.csv</code> ذخیره کنید. 
</font>
</p>

In [5]:
covid_data.duplicated().sum()

np.int64(0)

In [6]:
covid_data['Total_Cases'] = covid_data['Incident_Rate'].apply(lambda x: x * 100000)

In [7]:
top10cases = pd.DataFrame(covid_data.groupby('Country_Region')['Total_Cases'].sum())
top10cases = top10cases.sort_values(by=['Total_Cases'], ascending=False).head(10)

In [8]:
top10cases.to_csv('top10cases.csv', header=False)

In [9]:
pd.read_csv('top10cases.csv', header=None)

          0             1
0        US  1.060653e+12
1    Russia  1.084148e+10
2    Brazil  9.817550e+09
3      Peru  6.967909e+09
4  Colombia  6.661217e+09
5     Spain  5.766248e+09
6     Chile  4.348631e+09
7     Italy  3.359897e+09
8   Ukraine  3.171402e+09
9     India  3.116931e+09

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت دوم
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در ادامه می‌خواهیم ببینیم چه کشورهایی هیچ مورد بهبودیافته‌ای در این روز گزارش نکرده‌اند.
ابتدا ردیف‌هایی که مقدار هر سه ستون <code>Confirmed</code>، <code>Deaths</code> و <code>Recovered</code> آن‌ها صفر است را از دیتافریم اصلی حذف کنید. سپس تنها مواردی که هیچ مورد بهبودیافته‌ای نداشته‌اند را نگه داشته و
پاسخ را، به ترتیب نزولی موارد تایید شده‌ی ابتلا، در فایلی به نام <code>norecovered.csv</code> ذخیره کنید.
<br>
توجه داشته باشید که فایل شما باید شامل ۴ ستون باشد که به ترتیب نام کشور/منطقه، تعداد موارد تایید شده، موارد فوتی و موارد بهبود یافته باشد.
</font>
</p>

In [10]:
covid_data = covid_data[~(covid_data[["Recovered", "Confirmed", "Deaths"]] == 0).all(axis=1)]

In [11]:
no_recovered = covid_data.loc[covid_data["Recovered"] == 0].sort_values(by=["Confirmed"], ascending=False)
no_recovered.to_csv('norecovered.csv', header=False)

In [12]:
pd.read_csv('norecovered.csv', header=None).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,3943,3943,NaN,NaN,England,United Kingdom,2020-11-11 05:25:30,52.355500,-1.174300,1053330,58514,0.0,1009504.0,"England, United Kingdom",1881.712554,4.160709,1.881713e+08
1,461,461,NaN,NaN,Lima,Peru,2020-11-11 05:25:30,-11.766533,-76.604498,415467,40117,0.0,375350.0,"Lima, Peru",3908.989980,9.655881,3.908990e+08
2,844,844,6037.0,Los Angeles,California,US,2020-11-11 05:25:30,34.308284,-118.228241,326034,7202,0.0,318832.0,"Los Angeles, California, US",3247.639456,2.208972,3.247639e+08
3,1263,1263,17031.0,Cook,Illinois,US,2020-11-11 05:25:30,41.841448,-87.816588,227425,5667,0.0,221758.0,"Cook, Illinois, US",4415.819634,2.491810,4.415820e+08
4,3397,3397,48201.0,Harris,Texas,US,2020-11-11 05:25:30,29.858649,-95.393395,213380,2871,0.0,165875.0,"Harris, Texas, US",3580.190205,1.701374,3.580190e+08

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت سوم
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
اکنون می‌خواهیم اوضاع سایر کشورها را با کشور خودمان مقایسه‌ای کنیم! از این روی می‌خواهیم ببینیم کدام کشورها با وجود این‌که مبتلایان بیشتری از ما داشته‌اند، مرگ و میر کمتری ثبت کرده‌اند.
<br>
پاسخ را در فایلی به نام <code> vsiran.csv </code> ذخیره کنید. فایل پاسخ باید حاوی ۴ ستون باشد که نام کشور/منطقه، موارد تایید شده، موارد فوت‌شده و موارد بهبودیافته را به‌صورت نزولی بر اساس تعداد موارد تایید شده در بر داشته باشد.
</font>
</p>

In [13]:
iran_confirmed = covid_data['Confirmed'].loc[covid_data['Country_Region'] == "Iran"].values[0]
iran_deaths = covid_data['Deaths'].loc[covid_data['Country_Region'] == "Iran"].values[0]

In [14]:
vsiran = covid_data.loc[(covid_data['Confirmed'] > iran_confirmed) & (covid_data['Deaths'] < iran_deaths)]
vsiran = vsiran[["Country_Region", "Confirmed", "Deaths", "Recovered"]].sort_values(by=["Confirmed"], ascending=False)
vsiran.to_csv('vsiran.csv', header=False)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
قسمت چهارم
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazir" size=3>
در ادامه می‌خواهیم ادعای سخنگوی وزارت بهداشت کشوری را ارزیابی کنیم که ادعا می‌کند کشورش با توجه به آمار فوتی‌هایشان در این روز، جزو ۲۰ درصد برتر جهان است (هنوز در آن زمان عبارتی مثل «کشورهای برتر یک درصد جهان» کشف نشده بود :) ).
<br>
ما تعداد مرگ‌های گزارش‌شده را به تنهایی کافی نمی‌دانیم و فرض کنید برای راستی‌آزمایی این ادعا می‌خواهیم از شاخص ساده‌ای چون <b style="color:#0099cc">نسبت تعداد متوفیان به مبتلایان</b> استفاده کنیم. البته برای اینکه اینقدر هم دیگر ساده نباشد (!)، می‌خواهیم کشورهایی که مبتلایان تایید شده‌ی کمی در این روز داشته‌اند را در نظر نگیریم و برای این کار ۲۰ درصد کشورهایی که کمترین مبتلایان را داشته‌اند را نیز کنار می‌گذاریم و سپس شاخص مربوطه را برای کشورهای باقی‌مانده لحاظ می‌کنیم.
<br>
مقدار شاخص را در ستونی به نام <code>death_ratio</code> ذخیره کرده و
فهرست ۲۰ درصد برتر را به همراه مقدار شاخص ذکر شده در فایلی به نام 
    <code>20percent.csv</code> ذخیره کنید.

</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:orange">توجه:</b>
آن دسته از ردیف‌هایی که مقدار ستون <code>Confirmed</code> آن‌ها برابر صفر است را در نظر نگرفته و حذف کنید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<b style="color:green">راهنمایی:</b>
دیتافریم حاصل شامل ۳۰ ردیف خواهد بود.
</font>
</p>

In [15]:
agg_data = pd.DataFrame(covid_data.groupby('Country_Region')[['Deaths', 'Confirmed']].agg('sum'))
thresh_20 = agg_data['Confirmed'].quantile(0.2)
agg_data = agg_data.loc[agg_data['Confirmed'] >= thresh_20]
agg_data

                    Deaths  Confirmed
Country_Region
Afghanistan           1574      42297
Albania                579      25294
Algeria               2077      63446
Andorra                 75       5477
Angola                 308      12816
...                    ...        ...
Venezuela              834      95445
West Bank and Gaza     533      59422
Yemen                  601       2063
Zambia                 350      16997
Zimbabwe               255       8610

[152 rows x 2 columns]

In [16]:
agg_data['death_ratio'] = agg_data.apply(lambda row: row['Deaths'] / row['Confirmed'], axis=1)

In [17]:
thresh_80 = agg_data['death_ratio'].quantile(0.8)
agg_data = agg_data.loc[agg_data['death_ratio'] > thresh_80]

In [18]:
percent20 = agg_data.sort_values(by=['death_ratio'], ascending=False)
percent20.to_csv('20percent.csv', header=False)