<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
 شهر‌های پرجمعیت
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این تمرین با اطلاعات بیش از ۴۰هزار شهر در قالب یک دیتافریم مواجه می‌شوید و با هدف تمرین کتابخانه‌های <code>pandas</code> و <code>numpy</code> باید تغییراتی روی این دیتافریم ایجاد کنید.   
</font>
</p>

In [48]:
import numpy as np
import pandas as pd

In [49]:
import warnings
warnings.filterwarnings('ignore')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
داده‌ها را از فایل اکسل <code>worldcities.xlsx</code> که در پوشه تمرین قرار دارد بخوانید و در متغیر 
<code>df</code>
 ذخیره کنید.

</font>
</p>

In [50]:
# load data
df = pd.read_excel('worldcities.xlsx')
df.head()

,ville,ville_ascii,lat,lng,pays,iso2,iso3,admin_nom,capital,population,id
0,A Coruña,A Coruna,43.3667,-8.3833,Spain,ES,ESP,Galicia,minor,245468.0,1.724417e+09
1,A Yun Pa,A Yun Pa,13.3939,108.4408,Vietnam,VN,VNM,Gia Lai,minor,53720.0,1.704946e+09
2,Aabenraa,Aabenraa,55.0444,9.4181,Denmark,DK,DNK,Syddanmark,minor,16401.0,1.208000e+09
3,Aachen,Aachen,50.7756,6.0836,Germany,DE,DEU,North Rhine-Westphalia,minor,249070.0,1.276806e+09
4,Aadorf,Aadorf,47.4939,8.8975,Switzerland,CH,CHE,Thurgau,NaN,9036.0,1.756023e+09

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
حذف و نام‌گذاری ستون‌ها
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
ستون‌های
<code>id</code>،
<code>‌capital</code>،
<code>ville_ascii</code> 
و 
<code>admin_nom</code>
 را از دیتافریم حذف نمایید.
سپس نام ستون‌های 
<code>ville</code> 
و 
<code>pays</code>
 که به زبان فرانسوی نامگذاری شده‌اند را به ترتیب به 
<code>city</code> 
و 
<code>country</code>
تغییر دهید.
</font>
</p>

In [51]:
# drop and rename
df = df.drop(['admin_nom', 'id', 'capital', 'ville_ascii'], axis=1)
df.rename(columns={"ville": "city", "pays": "country"}, inplace=True)
df.head()

       city      lat       lng      country iso2 iso3  population
0  A Coruña  43.3667   -8.3833        Spain   ES  ESP    245468.0
1  A Yun Pa  13.3939  108.4408      Vietnam   VN  VNM     53720.0
2  Aabenraa  55.0444    9.4181      Denmark   DK  DNK     16401.0
3    Aachen  50.7756    6.0836      Germany   DE  DEU    249070.0
4    Aadorf  47.4939    8.8975  Switzerland   CH  CHE      9036.0

In [52]:
df.shape

(44667, 7)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
فیلتر داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
شهر‌های با جمعیت کمتر از ۱ میلیون نفر  را از دیتافریم حذف کرده (شهر‌های با جمعیت دقیقا ۱ میلیون نفر در دیتافریم بمانند) و سپس نوع داده‌های ستون 
<code>population</code>
 را از 
 <code>float</code>
  به
  <code>int32</code>
   تبدیل نمایید.
</font>
</p>

In [53]:
# filter data
df = df.loc[df['population'] > 1000000]
df.shape

(773, 7)

In [54]:
# change type population
df['population'] = df['population'].astype('int32')
df.dtypes

city           object
lat           float64
lng           float64
country        object
iso2           object
iso3           object
population      int32
dtype: object

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در مراحل بعدی می‌خواهیم برخی مقادیر دیتافریم را تغییر دهیم و جهت داوری تغییرات صورت گرفته تاکنون نیاز است یک کپی از <code>df</code> داشته باشیم. بدین منظور از تابع  <code>copy</code> استفاده می‌کنیم.
به طور کلی استفاده از مساوی برای دیتافریم‌ها در پانداز مانند نامپای عمل می‌کنند و تنها یک رفرنس جدید به همان دیتافریم اضافه می‌شود بنابراین تغییر دادن هر کدام از دیتافریم‌ها باعث تغییر دیگری نیز می‌شود.
    استفاده از تابع <code>copy</code> این قابلیت را برای ما ایجاد می‌کند که یک کپی از دیتافریم اولیه دریافت کنیم و تغییر یکی تاثیری روی دیگری نداشته باشد.
<br>
</font>
</p>

In [55]:
first_df = df.copy()

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
حذف داده‌های تکراری و گم‌شده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
نخست ردیف‌های تکراری دیتافریم و سپس ردیف‌هایی که بیش از یک مورد (۲ مورد و بیش‌تر) از اطلاعات آن‌ها گم‌شده است را از دیتافریم حذف نمایید.
</font>
</p>

In [56]:
# remove duplicated and missed values
df.dropna(thresh=5, inplace=True)
df.shape

(771, 7)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
پر کردن داده‌ها گم‌شده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در ادامه این تمرین قصد داریم محاسباتی را بر روی ستون‌های 
<code>lat</code> و 
<code>lng</code>
 انجام دهیم، اما در چند ردیف از دیتافریم مقادیر یکی از این دو ستون ثبت نشده است؛ از این رو در این بخش قصد داریم مقادیر مفقوده در این دو ستون را با میانگین همان مولفه در همان کشور پر نماییم. به عنوان مثال چنانچه مقدار <code>lat</code> 
 برای مشهد ثبت نشده باشد، میانگین <code>lat</code>  در دیگر شهر‌های ایران را محاسبه کرده و به عنوان <code>lat</code>  برای شهر مشهد در نظر می‌گیریم.
</font>
</p>

In [89]:
# fill missing values of 'lat' and 'lng' columns
df['lat'].fillna(df['lat'].groupby(df['country']).transform('mean'), inplace=True)
df['lng'].fillna(df['lng'].groupby(df['country']).transform('mean'), inplace=True)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
محاسبه فاصله از تهران
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این بخش قصد داریم فاصله هر یک از شهر‌ها را با تهران حساب کنیم. بدین منظور از فرمول هاورسین استفاده خواهیم کرد. این فرمول بر اساس طول جغرافیایی (Logitude) و عرض جغرافیایی (Latitude)  دو نقطه در سطح یک کره، فاصله آنها را حساب می‌کند.
فرمول محاسبه فاصله هاورسین در ادامه آورده شده است. برای اطلاعات بیشتر در رابطه با آن می‌توانید به این
<a href="https://www.movable-type.co.uk/scripts/latlong.html"> لینک</a>
 مراجعه کنید. 
در این بخش از شما خواسته شده است، نخست با توجه به فرمول هاورسین و مقادیر طول و عرض جغرافیایی تهران که از دیتافریم استخراج می‌کنید تابع  <code>haversin_from_teh</code>  را تکمیل کرده تا فاصله هر شهر از تهران را محاسبه کند و سپس با استفاده از این تابع، 
فاصله هر شهر از تهران را در ستون
<code>distance_from_tehran</code>
در دیتافریم درج نمایید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
فرمول هاورسین:
</font>
</p>



$\lambda_1$, $\lambda_2$ : longitudes of the two points in radians (lng)

$\varphi_1$, $\varphi_2$ : the latitudes of the two points in radians (lat)

$d$ : distance between two cities


$$
r = 6371
$$
$$
a = \sin^2\left(\frac{\varphi_2-\varphi_1}{2}\right) + \cos(\varphi_1)\cos(\varphi_2)\sin^2\left(\frac{\lambda_2-\lambda_1}{2}\right)
$$
$$
d = 2r \operatorname{atan2}\left(\sqrt{a}, \sqrt{1 -a}\right)
$$

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
<code>تذکر:</code>
دقت کنید که مقادیر طول و عرض جغرافیایی ثبت شده در دیتافریم به درجه می‌باشد و برای استفاده از رابطه فوق باید به رادیان تبدیل گردد. همچنین توجه کنید ملاک ارزیابی پاسخ شما فرمول فوق و طول و عرض جغرافیایی تهران که در همین دیتافریم درج شده، می‌باشد.
</font>
</p>

In [61]:
df.loc[df['city'] == 'Tehran']

         city      lat      lng country iso2 iso3  population
39301  Tehran  35.6892  51.3889    Iran   IR  IRN    14148000

In [96]:
def haversine_from_teh(lat, lng):
    r = 6371

    lat, lng = np.radians(lat), np.radians(lng)
    lat_teh, lng_teh = np.radians(35.6892), np.radians(51.3889)

    cos_lat_teh = np.cos(lat_teh)
    cos_lat = np.cos(lat)
    sin2lat = np.sin((lat - lat_teh) / 2) ** 2
    sin2lng = np.sin((lng - lng_teh) / 2) ** 2

    a = sin2lat + (cos_lat_teh * cos_lat * sin2lng)
    d = (2 * r) * np.atan2(np.sqrt(a), np.sqrt(1 - a))
    return d

In [100]:
df['distance_from_tehran'] = haversine_from_teh(df['lat'], df['lng'])

In [101]:
df.head()

,city,lat,lng,country,iso2,iso3,population,distance_from_tehran
19,Aba,5.1167,7.3667,Nigeria,NG,NGA,1530000,5634.737243
83,Abidjan,5.3167,-4.0333,Côte d'Ivoire,CI,CIV,4980000,6575.533770
121,Abu Dhabi,24.4667,54.3667,United Arab Emirates,AE,ARE,1483000,1280.150009
131,Abuja,9.0667,7.4833,Nigeria,NG,NGA,3770000,5331.673578
169,Accra,5.5500,-0.2000,Ghana,GH,GHA,2388000,6230.918394

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مرتب‌سازی و دخیره دیتافریم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
حال شهر‌ها را بر اساس حروف الفبا (به صورت صعودی) و سپس بر اساس مقدار ستون 
<code>lat</code>
(به صورت نزولی)
 مرتب کرده و دیتافریم <code>df</code> را بدون نمایه‌هایش (index) درون فایلی به نام <code>distances.csv</code> ذخیره کنید. 
</font>
</p>

In [108]:
df = df.sort_values(
    by=['country', 'lat'],
    ascending=[True, False]
).reset_index(drop=True)

df.to_csv('distances.csv', index=False)


<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
عمل فوق را بر روی دیتافریم 
<code>first_df</code>
نیز اجرا کنید و با نام 
<code>cities.csv</code>
ذخیره کنید (مرتب‌سازی بر اساس نام شهر (به صورت صعودی) و سپس بر اساس مقدار ستون 
<code>lat</code>
(به صورت نزولی) و ذخیره دیتافریم بدون نمایه).
</font>
</p>

In [107]:
first_df = first_df.sort_values(
    by=['country', 'lat'],
    ascending=[True, False]
).reset_index(drop=True)

df.to_csv('cities.csv', index=False)